### ISSUE TITLE
On user profile website link is not a clickable link, only a textfield

### ISSUE THREAD

**Issue by KostyalBalint** [kir-dev/pek-next#357]
A magyar leírás lent található

## English description

If a user adds a website to her/his profile, the weblink shown will not turn to a clickable link. 

---

## Magyar leírás

Ha a felhasználó hozzáad egy weboldalt a profiljához, a megjelenő link nem lesz kattintható.

**Comment by SepsiLaszlo** [comment]
@KostyalBalint Thank you for submitting this issue! 
The enhancement is live in production!
It only works for URL-s, so in your case [http://www.areba.hu](http://www.areba.hu) should work fine!
